create table public.authors (
  id bigint generated by default as identity not null,
  user_name text not null,
  user_xhs_id text not null,
  subscribers integer not null default 0,
  followers integer not null default 0,
  likes integer not null default 0,
  profile_url text null,
  created_at timestamp with time zone not null default now(),
  other_notes jsonb not null default '[]'::jsonb,
  report text null,
  constraint authors_pkey primary key (id),
  constraint authors_user_xhs_id_key unique (user_xhs_id)
) TABLESPACE pg_default;

create index IF not exists idx_authors_user_xhs_id on public.authors using btree (user_xhs_id) TABLESPACE pg_default;

create index IF not exists idx_authors_created_at on public.authors using btree (created_at) TABLESPACE pg_default;


create table public.notes (
  id bigint generated by default as identity not null,
  author_id bigint not null,
  title text not null,
  description text null,
  likes integer null default 0,
  collects integer null default 0,
  is_top10 boolean not null default false,
  raw_json jsonb not null,
  created_at timestamp with time zone not null default now(),
  constraint notes_pkey primary key (id),
  constraint notes_author_id_fkey foreign KEY (author_id) references authors (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_notes_author_id on public.notes using btree (author_id) TABLESPACE pg_default;

create index IF not exists idx_notes_is_top10 on public.notes using btree (is_top10) TABLESPACE pg_default;

create index IF not exists idx_notes_created_at on public.notes using btree (created_at) TABLESPACE pg_default;